fix info on meeting cadence
cdfoundation/sig-interoperability pull request #67
Opened 2021-05-07 08:52 UTC by MarckK

2021-05-07 09:43 UTC, fdegir approved these changes

2021-05-07 09:45 UTC, fdegir commented on README.md
> +SIG Interoperability meets first and third Thursdays at 16:00UTC. (*See your timezone [here](https://time.is/1600_in_UTC)*).
can you please update the time as well? It is 15:00UTC during summer time.

2021-05-07 09:45 UTC, fdegir requested changes
meeting time needs to be updated as well.

2021-05-07 10:14 UTC, oleg-nenashev approved these changes

2021-05-10 08:10 UTC, fdegir commented
Thanks!

2021-05-13 08:52 UTC, merged